[package]
name = "scheduler"
version = "0.1.0"
authors = ["Harrison Brewton <hbrewton@wisc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
